name: CMake

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Libraries
      run: |
        sudo apt-get update
        sudo apt-get -y install lcov cppcheck clang-tidy clang-format valgrind
        sudo apt-get install python3-pip
        pip3 install cpplint  
    
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DWITH_COVERAGE=ON -DSANITIZE=ON -DWITH_CLANG_TIDY=ON

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        cd tests/
        ctest -C ${{env.BUILD_TYPE}}
        cd ..
        lcov -t tests/ -d impl/ -c -o coverage.info
        genhtml -o report coverage.info
      
    - name: Linters, Formatting
      run: |
        clang-format -i impl/*.[h,c] tests/*.cpp main.c
        cppcheck -q --enable=all ./impl/ --suppress=missingIncludeSystem --suppress=unusedFunction
        clang-tidy impl/*.[h,c] -warnings-as-errors=* -extra-arg=-std=c11 -p build/
        cpplint --extensions=c impl/*.c
    
    - name: Configure CMake (Valgrind)
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        rm -rf ${{github.workspace}}/build
        cmake -B ${{github.workspace}}/build
    
    - name: Build (Valgrind)
      run: cmake --build ${{github.workspace}}/build

    - name: Valgrind
      working-directory: ${{github.workspace}}/build
      run: |
        valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all -s tests/test_io
        valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all -s tests/test_data
        valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all -s tests/test_logic
        valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all -s tests/test_utils
        valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all -s ./hw1_main ../resources/software.txt
